[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    me-no-dev/AsyncTCP @ ^1.1.1
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA @ ^3.1.0
    adafruit/DHT sensor library@^1.4.6
build_flags =
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -DDEVICE_TYPE=1
    ;-DSWITCH_PIN=4
    -DDEBUG_ENABLED=1
    ;-DDEBUG_MQTT=1
    ;-DWDT_ENABLED=1
    ;-DWDT_TIMER_MS=5000
    ;-DMQTT_PUBLISH_RESET_REASON=1
    ;-DMQTT_IGNORE_PUBLISH_NORMAL_RESET_REASONS=1
    ;-DWDT_TEST=1

[env:esp8266]
platform = espressif8266
board = nodemcu
framework = arduino
monitor_speed = 115200
upload_speed = 460800
monitor_filters = direct ;ANSI
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA @ ^2.2.8
    adafruit/DHT sensor library@^1.4.6
build_flags = 
    -Wno-sign-compare
    -Wno-uninitialized
    -DDEVICE_TYPE=1
    ;-DSWITCH_PIN=14
    
    -DMAGIC_VALUE=0x5A6F
    -DVERSION=\"1.4\"   
    

    ;LED
    -DSTATUS_LED_PIN=2
    -DLED_INVERTED=1
    
    ; Device features
    ; -DOTA_ENABLED=0
    ; -DMQTT_ENABLED=0
    ; -DWDT_ENABLED=0
    ; -DWIFI_ENABLED=0

    -DDEBUG_ENABLED=1
    -DDEBUG_WIFI_ENABLED=1
    
    

    ; Logging features 
    ; -DLOG_SENSOR=0
    ; -DLOG_CONFIG=0
    ; -DLOG_FAN=0
    ; -DLOG_MQTT=0
    ; -DLOG_WIFI=0
    ; -DLOG_WEB=0
    ; -DLOG_AP=0
    ; -DLOG_OTA=0

    
    
    ; MQTT features
    ; -DMQTT_RESET_ENABLED=1
    ; -DMQTT_PUBLISH_RSSI=0
    
    ; WEB features
    ; -DWEB_RESET_ENABLED=1
    
    ; WDT features
    ; 
    ;-DWDT_TIMER_MS=1000
    ;-DMQTT_PUBLISH_RESET_REASON=1
    ;-DMQTT_IGNORE_PUBLISH_NORMAL_RESET_REASONS=1
      
board_build.flash_size = 4MB
board_build.flash_mode = dout
