[common]
framework = arduino
monitor_speed = 115200
upload_speed = 460800
monitor_filters = direct
build_flags =
  -DMONITOR_SPEED=115200
  -DDEVICE_TYPE=1
  -DVERSION=\"1.9.0\"
  -DMAGIC_VALUE=0x5A6D
  -DPB_ENABLE_MALLOC=0
  -DPB_FIELD_16BIT=1
  

; ================================================================
; 0. ESP 8266  — WIFI/AP/MQTT
; ================================================================
[env:esp8266]
platform = espressif8266@~4.1.0
board = nodemcu
extends = common
upload_port = /dev/cu.usbserial-1420
monitor_port = /dev/cu.usbserial-1420
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA @ ^2.2.8
    adafruit/DHT sensor library@^1.4.6
build_flags =
  ${common.build_flags}
    -Wno-sign-compare
    -Wno-uninitialized
    -DTRANSPORT_TYPE=0           # 0-MQTT, 1-ZIGBEE, 3-MATTER
    -DSWITCH_PIN=14
    -DPROVISIONING_METHOD=2      # 0=None, 1=BLE, 2=AP, 3 = AP+BLE
    -DFEATURE_RESET_BUTTON_ENABLED=0
; ================================================================
; 1. ESP32 — WIFI/AP/MQTT
; ================================================================
[env:esp32-ap_only]
platform = espressif32@6.4.0
board = esp32dev
extends = common
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA @ ^2.2.5
    adafruit/DHT sensor library@^1.4.6

upload_port = /dev/cu.usbserial-1420
monitor_port = /dev/cu.usbserial-1420
build_flags =
  ${common.build_flags}
  -DTRANSPORT_TYPE=0           # 0-MQTT, 1-ZIGBEE, 3-MATTER
  -DSWITCH_PIN=4
  -DLED_INVERTED=0
  -DSTATUS_LED_PIN=2
  ; -DFEATURE_WDT_ENABLED=1
  -DPROVISIONING_METHOD=2      # 0=None, 1=BLE, 2=AP, 3 = AP+BLE
  

; ================================================================
; 2. ESP32 (BLE) — WIFI/BLE/MQTT
; ================================================================
[env:esp32-ble_only]
platform = espressif32@6.4.0
board = esp32dev
board_build.partitions = huge_app.csv # BLE тяжелая
extends = common
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA @ ^2.2.5
    adafruit/DHT sensor library@^1.4.6

upload_port = /dev/cu.usbserial-1420
monitor_port = /dev/cu.usbserial-1420
build_flags =
  ${common.build_flags}
  -DTRANSPORT_TYPE=0           # 0-MQTT, 1-ZIGBEE, 3-MATTER
  -DSWITCH_PIN=4
  -DLED_INVERTED=0
  -DSTATUS_LED_PIN=2
  -DPROVISIONING_METHOD=1      # 0=None, 1=BLE, 2=AP, 3 = AP+BLE
  -DCORE_DEBUG_LEVEL=4        # только так будет показан список сетей в ESP BLE Prov!

[env:esp32-ble-ap]
platform = espressif32@6.4.0
board = esp32dev
board_build.partitions = huge_app.csv # BLE тяжелая
upload_port = /dev/cu.usbserial-1420
monitor_port = /dev/cu.usbserial-1420
extends = common
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA @ ^2.2.5
    adafruit/DHT sensor library@^1.4.6

build_flags =
  ${common.build_flags}
  -DTRANSPORT_TYPE=0           # 0-MQTT, 1-ZIGBEE, 3-MATTER
  -DSWITCH_PIN=4
  -DLED_INVERTED=0
  -DSTATUS_LED_PIN=2
  -DFEATURE_WDT_ENABLED=1
  -DPROVISIONING_METHOD=3      # 0=None, 1=BLE, 2=AP, 3 = AP+BLE
  -DCORE_DEBUG_LEVEL=4       # только так будет показан список сетей в ESP BLE Prov!

[env:ESP32-s3]
platform = espressif32@6.4.0
board = esp32dev
board_build.partitions = huge_app.csv # BLE тяжелая
upload_port = /dev/cu.usbserial-1420
monitor_port = /dev/cu.usbserial-1420
extends = common
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA @ ^2.2.5
    adafruit/DHT sensor library@^1.4.6

build_flags =
  ${common.build_flags}
  -DTRANSPORT_TYPE=0           # 0-MQTT, 1-ZIGBEE, 3-MATTER
  -DSWITCH_PIN=4
  -DLED_INVERTED=0
  -DSTATUS_LED_PIN=2
  -DPROVISIONING_METHOD=3      # 0=None, 1=BLE, 2=AP, 3 = AP+BLE

; ================================================================
; 3. Модуль ESP32-C3 Super Mini 
; ================================================================
[env:esp32-c3-SuperMini]
platform = espressif32@6.4.0
board = esp32-c3-devkitm-1
board_build.partitions = huge_app.csv
upload_port = /dev/cu.usbmodem14201
monitor_port = /dev/cu.usbmodem14201
extends = common

lib_deps = 
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA @ ^2.2.5
    adafruit/DHT sensor library@^1.4.6
build_flags =
  ${common.build_flags}
  -DTRANSPORT_TYPE=0           # 0-MQTT, 1-ZIGBEE, 3-MATTER
  -DSWITCH_PIN=4
  -DRESET_PIN=9         # Кнопка BOOT на плате ESP32-C3 Super Mini
  -DSTATUS_LED_PIN=8    # Синий светодиод на плате ESP32-C3 Super Mini
  -DLED_INVERTED=1  
  -DI2C_SDA_PIN=4
  -DI2C_SCL_PIN=5
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DPROVISIONING_METHOD=2      # (у C3 есть BLE но он работает плохо и не работает одновременно с AP) // 0=None, 1=BLE, 2=AP
  -DCORE_DEBUG_LEVEL=4
  ; -DFEATURE_WDT_ENABLED=0
  
; 4. ESP32-C6 — MQTT ИЛИ ZigBee (выбор пользователя)
; ================================================================


; 4a. ESP32-C6 с MQTT (использует WiFi)
[env:esp32-c6-mqtt]
platform = espressif32@6.4.0
board = esp32-c6-devkitm-1
framework = espidf
extends = common
build_unflags = ${common.build_flags}
upload_port = /dev/cu.usbmodem14201
monitor_port = /dev/cu.usbmodem14201
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA @ ^2.2.5
    adafruit/DHT sensor library@^1.4.6
build_flags =
  ${common.build_flags}
  -DTRANSPORT_TYPE=0           # 0-MQTT, 1-ZIGBEE, 3-MATTER
  -DSWITCH_PIN=4
  -DLED_INVERTED=1
  -DSTATUS_LED_PIN=8
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DPROVISIONING_METHOD=1      # ← BLE

; 4b. ESP32-C6 с ZigBee (НЕ использует WiFi)
[env:esp32-c6-zigbee]
platform = espressif32@6.4.0
board = esp32-c6-devkitm-1
framework = espidf
extends = common
build_unflags = ${common.build_flags}
upload_port = /dev/cu.usbmodem14201
monitor_port = /dev/cu.usbmodem14201
lib_deps = 
  ; espressif/esp-zigbee-lib @ ^2.0.0
  ; espressif/esp-zigbee-sdk @ ^1.0.0
    # Для Zigbee нужны свои библиотеки (ESP-Zigbee-SDK)
build_flags =
  ${common.build_flags}
  -DTRANSPORT_TYPE=1           # 0-MQTT, 1-ZIGBEE, 3-MATTER
  -DSWITCH_PIN=4
  -DLED_INVERTED=1
  -DSTATUS_LED_PIN=8
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
