[common]
framework = arduino
monitor_speed = 115200
upload_speed = 460800
monitor_filters = direct
build_flags =
; Common sets   
    -DDEVICE_TYPE=1     ;1-Fan/2-Sensor/3-Switch
    -DVERSION=\"1.7.4\"
    ;
    -DMAGIC_VALUE=0x5A6B
    ; LED indicator (built-n for NodeMCU)
    -DSTATUS_LED_PIN=2
; Debugging
    -DDEBUG_ENABLED=1
    ;-DCORE_DEBUG_LEVEL=5
    ; Device class testing
    ; -DUSE_DEVICE_CLASS=0
    ; -DDEBUG_DEVICE_CLASS=1
    ; -DIGNORE_DEVICE_CRC=0
    ; -DTEST_DISABLE_WIFI=1
    ; -DTEST_DISABLE_MQTT=1
    ; -DTEST_DISABLE_SENSOR=1
    ; -DTEST_DISABLE_FAN=1
    ; -DTEST_DISABLE_WEB=1
    ; -DTEST_DISABLE_OTA=1
    ; -DTEST_DISABLE_FULL=1
; Detailed debugging for modules 
    -DDEBUG_WIFI_ENABLED=1
    ;-DDEBUG_OTA=1
    ;-DSIMULATE_EEPROM_MALFUNCTION=1

; Logging debug parts disabling
    -DLOG_LEVEL=4           ; 0=NONE, 1=ERROR,2=WARN,3=INFO,4=DEBUG
    -DLOG_CATEGORIES=0xFFFF ; Все категории
    -DLOG_USE_COLOR=1

; Device features disable
    -DOTA_ENABLED=1
    -DMQTT_ENABLED=1
    -DWDT_ENABLED=1
    -DWIFI_ENABLED=1

; MQTT features
    ; -DMQTT_RESET_ENABLED=1
    ; -DMQTT_PUBLISH_RSSI=0   
    ; -DMQTT_PUBLISH_VERSION=0   

; WEB features
    ; -DWEB_RESET_ENABLED=1    

; WDT features
    ;-DWDT_TIMER_MS=1000
    ;-DMQTT_PUBLISH_RESET_REASON=1
    ;-DMQTT_IGNORE_PUBLISH_NORMAL_RESET_REASONS=0

[env:esp32]
platform = espressif32@5.2.0
board = esp32dev
extends = common
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA @ ^2.2.5
    adafruit/DHT sensor library@^1.4.6


build_flags =
    ${common.build_flags}
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=0 
    -DSWITCH_PIN=4   
    -DLED_INVERTED=0

[env:esp8266]
platform = espressif8266@~4.1.0
board = nodemcu
extends = common
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit AHTX0 @ ^2.0.5
    ayushsharma82/ElegantOTA @ ^2.2.8
    adafruit/DHT sensor library@^1.4.6
build_flags = 
    ${common.build_flags}
    -Wno-sign-compare
    -Wno-uninitialized
    -DSWITCH_PIN=14   
    ;LED
    -DLED_INVERTED=1
    
 
      
board_build.flash_size = 4MB
board_build.flash_mode = dout

; @TODO
; [env:esp32-c6]
; platform = espressif32@6.5.0
; board = esp32-c6-devkitc-1
; framework = arduino
; build_flags = 
;     ${common.build_flags}
;     -DZIGBEE_MODE_ED
;     -DCORE_DEBUG_LEVEL=5
; board_build.partitions = zigbee.csv